const $=id=>document.getElementById(id);
const paths={outer:'M7 4l5-2 5 2 4 6-3 2-2-4v13H8V8l-2 4-3-2 4-6z M12 3v18 M8 14h2m4 0h2 M9 3l3 5 3-5',inner:'M8 3l4 2 4-2 6 5-4 4-2-2v11H8V10l-2 2-4-4 6-5z',top:'M8 6V5a4 4 0 018 0v1l4 3 2 10-4 1-2-9v10H8V11l-2 9-4-1L4 9l4-3z M9 6l3 3 3-3 M9 17h6',bottom:'M7 3h10l2 19h-6l-1-12-1 12H5L7 3z M7 6h10 M12 3v4',shoes:'M3 14l2-6 5 5 4 1 6 2 1 4H2v-4l1-2z M3 17h17 M10 13l-1 3m4-2-1 2',heart:'M20.8 4.6a5.5 5.5 0 00-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 00-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 000-7.8z',bag:'M5 7h14l2 14H3L5 7z M8 8V6a4 4 0 018 0v2',bookmark:'M6 3h12v19l-6-4-6 4V3z'};
const icon=(name)=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]}"></path></svg>`;
const catalog={outer:{label:'Outerwear',rail:'Outside',items:[['Utility Jacket',68,'Washed black · Relaxed fit',0],['Denim Jacket',58,'Slate blue · Boxy fit',1],['Tech Parka',82,'Olive · Lightweight shell',2],['Hooded Bomber',74,'Ink black · Oversized',3]]},inner:{label:'Essentials',rail:'Inside',items:[['Everyday Tee',24,'Chalk white · Cotton',0],['Ribbed Tank',19,'Soft white · Ribbed cotton',1],['Base Longsleeve',32,'Oat · Cotton blend',2],['Heavyweight Tee',28,'Coal · 240gsm cotton',3]]},top:{label:'Tops',rail:'Top',items:[['Studio Hoodie',52,'Ink · French terry',3],['Soft Knit',48,'Stone · Relaxed fit',0],['City Sweatshirt',42,'Ash · Brushed cotton',1],['Half-zip Knit',56,'Forest · Loose fit',2]]},bottom:{label:'Bottoms',rail:'Bottom',items:[['Wide Cargo',58,'Black · Wide leg',0],['Pleated Trousers',62,'Charcoal · Straight leg',1],['Utility Pants',54,'Black · Cotton twill',2],['Loose Denim',64,'Washed black · Wide leg',3]]},shoes:{label:'Shoes',rail:'Shoes',items:[['Canvas Low',45,'Black / white · Canvas',0],['Court Sneaker',65,'Cream · Everyday',1],['Trail Runner',78,'Graphite · Mesh',2],['Everyday Low',55,'Black · Classic sole',3]]}};
let category='outer',selected={outer:0,inner:0,top:0,bottom:0,shoes:0},look=0,bag=[],saved=[];const names=['SEOUL AFTER DARK','BLUE HOUR','OFF THE GRID','MIDNIGHT STUDIO'];let timer;
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('visible'),2300)}
function current(){return catalog[category].items[selected[category]]}function setLook(n){look=n;$('model').style.backgroundPositionX=`${n*100/3}%`;$('model').setAttribute('aria-label',`Sample outfit: ${catalog.outer.items[n][0]} with black cargo pants and sneakers`);document.querySelector('.look-label').innerHTML=`<span class="live-dot"></span>${names[n]}<span>0${n+1} / 04</span>`;updateSave()}
function updateSave(){const yes=saved.includes(look);$('save').classList.toggle('saved',yes);$('save').setAttribute('aria-pressed',yes);$('saveLabel').textContent=yes?'Saved':'Save'}
function render(){ $('rail').innerHTML=Object.entries(catalog).map(([key,c])=>`<button data-category="${key}" class="${category===key?'active':''}" aria-pressed="${category===key}">${icon(key)}${c.rail}</button>`).join('');$('categoryTitle').innerHTML=`${catalog[category].label} <span>04</span>`;$('products').innerHTML=catalog[category].items.map((p,i)=>`<button class="product ${i===selected[category]?'active':''}" data-item="${i}" aria-pressed="${i===selected[category]}" aria-label="${p[0]}, ${p[1]} dollars"><span class="thumb ${category==='outer'?'thumb-photo':''}" style="${category==='outer'?`background-position-x:${p[3]*100/3}%`:''}">${category==='outer'?'':icon(category)}</span><span class="product-name">${p[0]}</span><span class="product-price">$${p[1]}</span></button>`).join('');const p=current();$('selectedName').textContent=p[0];$('selectedMeta').textContent=p[2];$('price').textContent=`$${p[1]}`;}
function selectItem(n){selected[category]=(n+4)%4;if(category==='outer')setLook(current()[3]);else toast(`${current()[0]} selected · sample preview`);render();document.querySelector('.product.active').scrollIntoView({behavior:'smooth',block:'nearest',inline:'nearest'})}
$('rail').onclick=e=>{const b=e.target.closest('[data-category]');if(!b)return;category=b.dataset.category;render();$('products').scrollLeft=0};$('products').onclick=e=>{const b=e.target.closest('[data-item]');if(b)selectItem(Number(b.dataset.item))};$('prev').onclick=()=>selectItem(selected[category]-1);$('next').onclick=()=>selectItem(selected[category]+1);
$('saved').innerHTML=icon('bookmark');$('save').innerHTML=icon('heart');$('bag').innerHTML=icon('bag');$('save').onclick=()=>{if(saved.includes(look)){saved=saved.filter(x=>x!==look);toast('Look removed from My looks')}else{saved.push(look);toast('Look saved to My looks')}updateSave()};
function openSheet(title,html){$('sheetTitle').textContent=title;$('sheetBody').innerHTML=html;if(!$('sheet').open)$('sheet').showModal()}
function showSaved(){openSheet('My looks',saved.length?saved.map(n=>`<div class="sheet-row"><div class="swatch thumb-photo" style="background-position-x:${n*100/3}%"></div><div><strong>${names[n]}</strong><small>${catalog.outer.items[n][0]}</small></div><button data-load="${n}">Try on ↗</button></div>`).join(''):'<div class="empty"><span>♡</span>A little space for your favorites.<br>Tap the heart to save your first look.</div>')}
function showBag(){openSheet(`Your bag (${bag.length})`,bag.length?bag.map((p,i)=>`<div class="sheet-row">${icon(p.category)}<div><strong>${p.name}</strong><small>Size ${p.size} · $${p.price}</small></div><button data-remove="${i}" aria-label="Remove ${p.name}">Remove</button></div>`).join('')+`<div class="total"><span>Subtotal</span><span>$${bag.reduce((s,p)=>s+p.price,0)}</span></div><p class="sheet-copy">This is a demo bag with sample items and prices. No payment or order will be placed.</p>`:'<div class="empty"><span>✧</span>Your next look starts here.<br>Add a piece from the fitting room.</div>')}
$('add').onclick=()=>{const p=current();openSheet(p[0],`<p class="sheet-copy">${p[2]}<br>Sample price · $${p[1]}</p><label class="sheet-copy" for="size">Choose your size</label><select id="size" style="display:block;width:100%;padding:14px;margin:10px 0 20px;border-radius:10px;background:#27222e;color:white;border:1px solid #ffffff33"><option>XS</option><option>S</option><option selected>M</option><option>L</option><option>XL</option></select><button class="primary" id="confirmAdd">Add to demo bag · $${p[1]}</button>`);$('confirmAdd').onclick=()=>{bag.push({name:p[0],price:p[1],category,size:$('size').value});$('bagCount').textContent=bag.length;$('sheet').close();toast(`${p[0]} added to bag`)}};
$('sheetBody').onclick=e=>{const load=e.target.closest('[data-load]'),remove=e.target.closest('[data-remove]');if(load){category='outer';selected.outer=Number(load.dataset.load);setLook(selected.outer);render();$('sheet').close()}if(remove){bag.splice(Number(remove.dataset.remove),1);$('bagCount').textContent=bag.length;showBag()}};
$('details').onclick=()=>openSheet('The look',`<p class="sheet-copy">${names[look]}<br>${catalog.outer.items[look][0]} / White tee / Black cargo pants / Canvas sneakers</p><div class="sheet-row"><div><strong>Relaxed layers. Clean proportions.</strong><small>Inspired by everyday Seoul streetwear.</small></div></div><p class="sheet-copy">Demo preview: outerwear switches between four prepared outfits. Other categories let you browse and add sample pieces; they do not change the model yet. Live AI try-on is not connected.</p>`);
$('close').onclick=()=>$('sheet').close();$('sheet').onclick=e=>{if(e.target===$('sheet')){const r=$('sheet').getBoundingClientRect();if(e.clientY<r.top||e.clientX<r.left||e.clientX>r.right)$('sheet').close()}};$('saved').onclick=showSaved;$('looksTab').onclick=showSaved;$('bag').onclick=showBag;$('bagTab').onclick=showBag;$('roomTab').onclick=()=>{if($('sheet').open)$('sheet').close();category='outer';render()};render();setLook(0);
